### ISSUE TITLE
No Parallax View

### ISSUE THREAD

**Issue by gotnull** [algomystic/TheParallaxView#14]
I don't see the parallax when the application loads:

![img_1970](https://user-images.githubusercontent.com/578908/37072270-a39993e6-2214-11e8-8003-240f6d5b160a.PNG)

I'm using the exact same version of Unity 2017.3.0f3 and Xcode 9.2 as yourself. It builds, compiles and runs successfully.

iPhone X 11.2.6

**Comment by algomystic** [comment]
Load the HeadTrack3D scene
To see a good preview, set Game view to 2436 x 1125 pixels (which is iPhone Landscape res)

**Comment by algomystic** [comment]
did you get it to work?

**Comment by li8911255** [comment]
where can I find the HeadTrack3D scene? :(

**Comment by gotnull** [comment]
I couldn’t figure out what you meant by loading the Headtrack 3D scene. Is this meant to be done through Unity before it’s built or through Xcode?

**Comment by gotnull** [comment]
Can you also elaborate on setting the Game view dimensions?

**Comment by L4Z3RC47** [comment]
The HeadTrack3D scene is the scene within unity. You can also find the HeadTrack3D.unity file in the Assets folder and open that from the finder. When this scene is open you must add it to your build settings within Unity for it to be included in what Unity exports to XCode. From your screen shot it looks like you may have accidentally built the default Unity scene?

**Comment by algomystic** [comment]
README has been updated with detailed build instructions. Follow them and file another issue if it still doesn't work. Closing

**Comment by gotnull** [comment]
I'm not sure why you closed this. I'm still not seeing the ParallaxView properly.

I've loaded the HeadTrack3D scene within Unity and then I build and run. It opens Xcode, it compiles and the app is loaded to the device.

The problem is there's no parallax view. All the settings and buttons appear to be in the correct place.

I've uploaded a video: https://vimeo.com/261934565 (Password: parallax)

**Comment by algomystic** [comment]
I can see from the video you have not built the latest version. I can also
see that it is not limited to "landscape left" orientation - this means the
project settings are not correct.

Clone/download the latest version, follow the new build instructions in the
README file and all will work fine. If you still have an issue after doing
so, open a new issue.

Peder
